### ISSUE TITLE
Missing OrderType in OrderTypeConverter

### ISSUE THREAD

**Issue by dlmac** [JKorf/Kraken.Net#1]
An order type from Kraken JSON data shows "ordertype": "stop market", which looks to be missing from the converter.

**Error:**
Cannot map enum. Type: Kraken.Net.Objects.OrderType, Value: stop market
Exception thrown: 'System.NullReferenceException' in Newtonsoft.Json.dll

**Method:**
var history = await client.GetTradeHistoryAsync(resultOffset: offset);

"TDSUTH-DO3XV-V67G37": {
        "ordertxid": "ODBUJA-CTRWB-YJSTLF",
        "postxid": "T5XXXZ-KAHYB-W6RQKR",
        "pair": "XXBTZUSD",
        "time": 1483734622.6224,
        "type": "sell",
        "ordertype": "stop market",
        "price": "877.55000",
        "cost": "1652.37592",
        "fee": "4.29618",
        "vol": "1.88294218",
        "margin": "550.79197",
        "misc": "closing"
      },

I can send full JSON if needed.

**Comment by JKorf** [comment]
Hm that's interesting. I'll add it to the enum. Do you know if there are any other types which might not be in the enum? I implemented the order types enum according to the Kraken api documentation at https://www.kraken.com/features/api#add-standard-order . The `stop market` order type is not in that list, which raises the question if there are any other types which aren't in that list.

**Comment by dlmac** [comment]
Maybe it is an order type that is no longer available to use. It is also only one trade of 1105. Could even be an error on Krakens end. Can't hurt to add it in, if it happens again I can reach out to Kraken Support.

![image](https://user-images.githubusercontent.com/372043/65440525-dbc00a80-ddf6-11e9-9c04-55cb464c691c.png)

**Comment by JKorf** [comment]
Fixed in the latest version
