### ISSUE TITLE
SymbolOrderBook does not Synchronize

### ISSUE THREAD

**Issue by BenDavison** [JKorf/Kraken.Net#10]
I am using SymbolOrderBook on Bittrex and Binance but when using the same implementation with Kraken the OrderBook only transitions from Disconnected to Connecting.  The trading pair call was successful so connectivity via client is ok (although socketClient used by SymbolOrderBook not proven).  Is this a known issue/work in progress?

**Comment by JKorf** [comment]
Hi, it works as far as I'm aware ( works on my machine ). 
Tested using a simple console application like this:
````C#
            var orderbook = new KrakenSymbolOrderBook("ETH/XBT", 25);           
            orderbook.Start();

            while (true)
            {
                Console.Clear();
                Console.WriteLine(orderbook.ToString(5));
                Thread.Sleep(500);
            }
````
Are there any errors in the logging? You can change logverbosit to debug when creating to orderbook: 
````C#
            var orderbook = new KrakenSymbolOrderBook("ETH/XBT", 25, new KrakenOrderBookOptions()
            {
                LogVerbosity = LogVerbosity.Debug
            }); 
````

**Comment by BenDavison** [comment]
Hi,

  I am subscribing to the StatusUpdates and never get the Syncing or Synced
state, just transitions to Connecting... I will have a play this evening
and let you know

  Many thanks

Ben

**Comment by BenDavison** [comment]
Hi Jan,

  Kraken may have changed their API?

  This is my simple integration test....  startResult.Success == false and
startResult.Error.Message ==  " Server error: Subscription depth not
supported"

 [Test]
        public void
IntegrationTest_ConnectToRealAPI_OrderBookTransitionsToSynchronized()
        {
            var synchornized = new ManualResetEvent(false);
            void onStatusChange(OrderBookStatus lastStatus, OrderBookStatus
newStatus)
            {
                Debug.WriteLine($"OrderBookStatus transitioned from
{lastStatus} to {newStatus}");
                if (newStatus == OrderBookStatus.Synced)
                    synchornized.Set();
            }

            Action<OrderBookStatus, OrderBookStatus> onStatusChangeAction =
onStatusChange;


            var symbolOrderBook = new KrakenSymbolOrderBook("ETH/XBT", 5);
            symbolOrderBook.OnStatusChange += onStatusChangeAction;
            var startResult = symbolOrderBook.Start();
            Assert.IsTrue(startResult.Success, startResult.Error.Message);
            synchornized.WaitOne(10000);
            Assert.AreEqual(OrderBookStatus.Synced, symbolOrderBook.Status);
        }

**Comment by BenDavison** [comment]
Jan,

  I have cracked it... I was limiting my book to < 25... the error was
misleading, if I use 25 as my limit then both Bitfinex and Kraken return
books and sync.  Which is great news for me as I now have both working :)

  Thanks for getting back to me... keep up the good work.

  If I need Poloniex before you get round to It I will start implementing
it on top of your CryptoExchange.Net
<https://github.com/JKorf/CryptoExchange.Net> repo and put it in GitHub.

  Cheers

Ben

**Comment by JKorf** [comment]
Thanks Ben, let me know if you need any help.
