### ISSUE TITLE
Order failed: [ServerError] EGeneral:Invalid arguments:volume 

### ISSUE THREAD

**Issue by hex** [JKorf/Kraken.Net#100]
**Describe the bug**
`Order failed: [ServerError] EGeneral:Invalid arguments:volume` received when placing an order.

**To Reproduce**
```csharp
var order = await client.SpotApi.Trading.PlaceOrderAsync(
       "XETHZEUR",
        OrderSide.Buy,
        OrderType.Market,
        0.0025m,
        orderFlags: new[] { OrderFlags.OrderVolumeExpressedInQuoteAsset });
```

**Expected behavior**
Order to succeed

How can I get more details about this error? The order min is `0.002` so I don't think that's the issue.

![Capture 2024-04-08 at 16 38 25](https://github.com/JKorf/Kraken.Net/assets/88922/d867a143-d742-41a0-917f-1b179efd665d)

**Comment by JKorf** [comment]
Hi, you're sending the order flag `OrderVolumeExpressedInQuoteAsset` which means the quantity you pass in is in EUR. So you're currently trying to buy 0.0025 EUR worth of ETH which fails as the order is too small. Either remove the flag or adjust the quantity to the Euro value

**Comment by hex** [comment]
Oh, you are right! Closing this.

Thank you!
