### ISSUE TITLE
Bug - Asset names do not get returned in krakenClient.SpotApi.Account.GetAvailableBalancesAsync()

### ISSUE THREAD

**Issue by tomShoutTheSecond** [JKorf/Kraken.Net#108]
**Describe the bug**
Asset names do not get returned in krakenClient.SpotApi.Account.GetAvailableBalancesAsync()

**To Reproduce**
Call krakenClient.SpotApi.Account.GetAvailableBalancesAsync() and await return value

**Expected behavior**
The returned KrakenBalanceAvailable objects should have asset names listed in their Asset properties

**Actual behavior**
The returned KrakenBalanceAvailable objects have Asset = "" which is the wrong value. The KrakenBalanceAvailable objects have the correct quantity values but no asset names can be found

<img width="794" alt="Screenshot 2024-06-06 at 20 04 53" src="https://github.com/JKorf/Kraken.Net/assets/42177014/47b23fb8-6405-4a4e-813a-80e4509337be">

**Comment by JKorf** [comment]
The result is a dictionary, so the asset was already available via the key of the dictionary, but I've added it on the response model as well in the latest version

**Comment by tomShoutTheSecond** [comment]
@JKorf Thanks for the quick fix on this! I can confirm it's working correctly in KrakenExchange.Net 4.7.0
