### ISSUE TITLE
Portfolio value?

### ISSUE THREAD

**Issue by hex** [JKorf/Kraken.Net#112]
Is there any method of getting the portfolio value that is displayed in the Kraken Pro dashboard?

**Comment by JKorf** [comment]
Try `restClient.SpotApi.Account.GetTradeBalanceAsync()`

**Comment by hex** [comment]
I tried that, but it returns numbers that don't make any sense to me. 🤔

**Comment by JKorf** [comment]
Oh that's weird. Seems to be okay for me

**Comment by hex** [comment]
I think it doesn't take in consideration staking/rewards system.

**Comment by JKorf** [comment]
Hm that's possible. You'll have to ask Kraken support about this
