### ISSUE TITLE
Issue with Order Updates in KrakenExchange.Net 4.10.0 and CryptoExchange.Net 7.10.0

### ISSUE THREAD

**Issue by sophiaciotti** [JKorf/Kraken.Net#115]
**Description:**
I am currently using KrakenExchange.Net version 4.10.0 alongside CryptoExchange.Net version 7.10.0. I’ve encountered an issue with the `SubscribeToOrderUpdatesAsync` method when subscribing to order updates.

**Issue:**
- The subscription generally works as expected; however, there are occasions when the order update event for a filled order is not raised within a 60-second timeframe.
- As a result, I sometimes send a cancellation request to refresh the order status.
- In these cases, I receive the order update indicating the cancellation, but upon further inspection, I discover that the order was actually filled up to 60 seconds prior to the cancellation.
- This means the filled event was never notified, which causes a discrepancy between the actual order status and the notifications received.

**Expected Behavior:**
The order update event should be consistently raised for all order status changes, including when an order is filled, within the expected timeframe.

**Actual Behavior:**
The event for a filled order is occasionally not raised in a timely manner, leading to delayed notifications and incorrect order management.

**Additional Information:**
This issue occurs sporadically, making it difficult to predict.

**Comment by JKorf** [comment]
Sorry for the delay. Is this still a problem?
I have never experienced this, and can't reproduce it, though you also mention that it happens sporradically. 
It's kinda hard to track, if you could provide some relevant logging or repro steps that would help.
