### ISSUE TITLE
Issue with date in Websocket API

### ISSUE THREAD

**Issue by vincentbillardfr** [JKorf/Kraken.Net#119]
Since recent updates to Kraken's Websocket V2 API, there is a problem with date formats, I get this error :
EGeneral:Invalid date format on expire_time

I noticed it with Add Order API, but I suppose it's a global problem. Kraken is not exactly using the "real" RFC3339 format, but only accepts something like that in UTC time:
Example: 2022-12-25T09:30:59.123Z

```
                EffectiveTime = startTime?.ToRfc3339String(),
                ExpireTime = expireTime?.ToRfc3339String(),
                Deadline = deadline?.ToRfc3339String(),
```

The .ToRfc3339String() method sould contains this format :
.ToString("yyyy-MM-dd'T'HH:mm:ss.fffK");

Of course, I suppose this can have many side effects, as this method is shared by different platform's libraries, so let's choose the optimal and safest way to fix this bug.

**Comment by vincentbillardfr** [comment]
After some testing, I noticed that Kraken API is not accepting milliseconds, so the datetime format should be :
.ToString("yyyy-MM-dd'T'HH:mm:ssK");

**Comment by JKorf** [comment]
Thanks for the report. I've fixed it in the latest version.
I went with .ToString("yyyy-MM-dd'T'HH:mm:ss'Z'") (UTC timezone) as this is how all other libraries also work.

**Comment by vincentbillardfr** [comment]
Works perfectly now. Thanks
