### ISSUE TITLE
[Feature] Trades History

### ISSUE THREAD

**Issue by CraftoHohenvels** [JKorf/Kraken.Net#122]
While `Account Balance` is already supported, it is not very good in terms of tracking orders places / assets bought.

Kraken offers `Get Trades History` as part of their API, but I haven't seen an implementation in this package.

Therefore please add this function. It is documented here: https://docs.kraken.com/api/docs/rest-api/get-trade-history

A reason this needs to be implemented? In my opinion being able to track the price you paid and fees are important to know when already having access to market data. Else this package is just a gimmick and nothing more - not really useful. But that is just my opinion.

I do really appreciate the work you have done already!

If you want I can implement this feature and create a pull request. Just leave a comment on this issue and I will get right to work!

Cheers

**Comment by JKorf** [comment]
Hello, the GetUserTradesAsync method is the implementation of that endpoint. I see some parameters are missing and I'll add them, but the endpoint itself is already available.
