### ISSUE TITLE
SpotApi.SubscribeToUserTradeUpdatesAsync 

### ISSUE THREAD

**Issue by rakewell** [JKorf/Kraken.Net#123]
Upgrading to the latest version I don't see this function any more (only in Futures), has it been replaced with SubscribeToOrderUpdatesAsync?

**Comment by JKorf** [comment]
Hi, yes the socket client was updated to the V2 API, where trade updates are now part of the OrderUpdates subscription (LastTradeXX properties)

**Comment by rakewell** [comment]
Thanks @JKorf , I probably should create a new request for this but would it be possible for you to integrate the assetVersion parameter into the assets and assetPairs calls as in the following:

?assetVersion=true

https://api.kraken.com/0/public/Assets?assetVersion=true
https://api.kraken.com/0/public/AssetPairs?assetVersion=true

This give the newer symbol definitions of assets such as BTC instead of XBT and XXBT. I have spoken to kraken support and they will modify their api eventually to the new standard but before then they suggest passing this parameter

**Comment by JKorf** [comment]
Ah I wasn't aware of those parameters (also isn't documented) but that's useful. I'll include them with next version

**Comment by rakewell** [comment]
Great, @JKorf, thank you very much

**Comment by JKorf** [comment]
The parameter is available in latest version
