### ISSUE TITLE
Edge case: Checksum when Order book update array has 5 elements

### ISSUE THREAD

**Issue by spcfran** [JKorf/Kraken.Net#15]
When the `book` feed message includes **both** asks and bid updates (when the array has 5 elements), it [also includes the checksum](https://docs.kraken.com/websockets/#message-book) (within the second object, apparently):

![image](https://user-images.githubusercontent.com/4398367/92787060-ab270700-f3a0-11ea-8a54-ef2a3cc15b18.png)

So it should be handled here:

https://github.com/JKorf/Kraken.Net/blob/b515d56885f80b1cb30d4cf6c84a1d988ba463b1/Kraken.Net/Converters/StreamOrderBookConverter.cs#L42

Why Kraken's stream service implementation has this weird edge case with 5 elements, instead of merging asks and bids within a single `{ a?, b?, c }` object, remains a mistery to me...

**Comment by TomasMichal** [comment]
@spcfran is right. When message includes both asks an bids, then Checksum is 0.

https://docs.kraken.com/websockets/#book-checksum

`[
    0,
    {
        "a": [
            ["0.05120", "0.00000500", "1582905486.493008"],
            ["0.05275", "0.00000500", "1582905486.493034"]
        ]
    },
    {
        "b": [
            ["0.04765", "0.00000500", "1582905486.493008"],
            ["0.04940", "0.00000500", "1582905486.493034"]
        ],
        "c": "974947235" <-- CRC32 checksum is here.
    },
    "book-1000",
    "XBT/USD"
]`

**Comment by JKorf** [comment]
This has been implemented
