### ISSUE TITLE
ValidateKrakenSymbol function not supporting all symbols

### ISSUE THREAD

**Issue by johannduplessis** [JKorf/Kraken.Net#21]
When trying to retrieve recent trades for REPV2XBT pair (which is a valid pair), the ValidateKrakenSymbol function returns false, making it impossible to use this pair with this library. The regex function on line 19 in KrakenHelpers.cs is probably to blame.

If I try and access this endpoint using a browser it works correctly.

The call is: https://api.kraken.com/0/public/Trades?pair=REPV2XBT

**Comment by JKorf** [comment]
Fixed in the latest version
