### ISSUE TITLE
Invalid Nonce

### ISSUE THREAD

**Issue by diplinfmarkodrews** [JKorf/Kraken.Net#23]
Ive just started implemting an interface to kraken api using your library.
The public calls to api, ive tried are working. But when I try to call private api functions, ill get invalid Nonce error.

"EAPI:Invalid nonce"

The provided keys are valid, i have also installed Net Time to ensure time synchronisation.

Is it possible to configure the receive window paramater?
Thanks a lot , your help is much appreciated.
Best Marko

**Comment by JKorf** [comment]
Kraken does not have a receiveWindow parameter. Have you by any chance ever send a higher nonce to the API in a request? Once a nonce has been sent to the API nonces sent after that can never be lower than that.
