### ISSUE TITLE
Implement order place/cancel over the WebSocket API

### ISSUE THREAD

**Issue by msnelling** [JKorf/Kraken.Net#25]
Can you please implement the 'Private' WebSocket API functions as per the Kraken docs? 
* [addOrder](https://docs.kraken.com/websockets/#message-addOrder)
* [cancelOrder](https://docs.kraken.com/websockets/#message-cancelOrder)
* [ownTrades](https://docs.kraken.com/websockets/#message-ownTrades)
* [openOrders](https://docs.kraken.com/websockets/#message-openOrders)

**Comment by JKorf** [comment]
Available in latest version
