### ISSUE TITLE
Kraken Quote and Base Asset is reversed in ICommonSymbol

### ISSUE THREAD

**Issue by Phmager** [JKorf/Kraken.Net#28]
I think the CommonName should be reversed for kraken, or am I wrong?

        string ICommonSymbol.CommonName => QuoteAsset + BaseAsset;

If we take a look at the api:
`"ETHUSDT":{"altname":"ETHUSDT","wsname":"ETH\/USDT","aclass_base":"currency","base":"XETH","aclass_quote":"currency","quote":"USDT", ... }`

the quote is the second part of the pair.

**Comment by JKorf** [comment]
You're right, I've fixed it in 1.4.1
