### ISSUE TITLE
Implementation of the new BalanceEx REST request

### ISSUE THREAD

**Issue by chalky66** [JKorf/Kraken.Net#30]
Hi,

is there a plan to implement the new Kraken BalanceEx REST request ?

i.e. (calling via the cmd line tool)

$ ./krakenapi BalanceEx

{"error":[],"result":{"ZUSD":{"balance":"21.9050","hold_trade":"17.2000"},"ZEUR":{"balance":"0.0203","hold_trade":"0.0000"},"KFEE":{"balance":"7328.19","hold_trade":"0.00"},"XXBT":{"balance":"0.0000000030","hold_trade":"0.0000000000"},"XETH":{"balance":"0.0000000000","hold_trade":"0.0000000000"}}}

**Comment by JKorf** [comment]
Do you have a link to the documentation for this new endpoint?

**Comment by chalky66** [comment]
Hi Jan,

here is the excerpt of an email that I received from a Kraken support
engineer recently, hope it helps....

Best Regards

Paul White

------
BalanceEx Example
The REST API *BalanceEx* endpoint will provide the information that you are
looking for, namely the amount of each account balance currency that is
withheld (due to existing open orders, for example).

(Note: this Is a newer endpoint and undocumented)

For example:

$ ./krakenapi BalanceEx


{"error":[],"result":{"ZUSD":{"balance":"21.9050",*"hold_trade":"17.2000"*},"ZEUR":{"balance":"0.0203","hold_trade":"0.0000"},"KFEE":{"balance":"7328.19","hold_trade":"0.00"},"XXBT":{"balance":"0.0000000030","hold_trade":"0.0000000000"},"XETH":{"balance":"0.0000000000","hold_trade":"0.0000000000"}}}


The withheld balance is provided by the hold_trade field for each account
balance currency (such as the $17.20 in the USD entry shown above, namely
"ZUSD":{"balance":"21.9050","hold_trade":"17.2000"}).

**Comment by JKorf** [comment]
Intresting. I've added the endpoint under GetAvailableBalances in the latest version.
