### ISSUE TITLE
Error: EGeneral:Invalid arguments:volume

### ISSUE THREAD

**Issue by rcearley2020** [JKorf/Kraken.Net#31]
I'm trying to test placing an order by calling the following code:
var order = kc.PlaceOrder("DOGEUSD", Objects.OrderSide.Buy, Objects.OrderType.Market, quantity: 10);

When I run the above, I get the error: Error: EGeneral:Invalid arguments:volume.  

Can anyone help?

Thank you.

**Comment by TomasMichal** [comment]
Hi, is pair DOGEUSD correct? I think the correct is XDGUSD and ordermin is 50...

var order = kc.PlaceOrder("XDGUSD", Objects.OrderSide.Buy, Objects.OrderType.Market, quantity: 50);

https://api.kraken.com/0/public/AssetPairs

**Comment by JKorf** [comment]
Based on the error message I'd say the order is too small as @TomasMichal mentioned

**Comment by rcearley2020** [comment]
It was both what TomasMichal and JKorf said.  Thank you.  That fixed it.
