### ISSUE TITLE
KrakenClientObj.GetDepositMethods(AssetDepotSymbol)   fails with "EFunding:Unknown withdraw key"

### ISSUE THREAD

**Issue by JRB202** [JKorf/Kraken.Net#33]
KrakenClientObj.GetDepositMethods(AssetDepotSymbol)   ' Fails with "EFunding:Unknown withdraw key" 
and returns DepositMethodsInfo.Data with empty value

The message "Unknown withdraw key" have nothing to do GetDepositMethods function called with Asset = "EUR"

Kraken Doc for this function is here :
https://docs.kraken.com/rest/#tag/User-Funding

Please note that this function doc says : 
Authorizations: API-Key AND API-Sign

Do you confirm V1.4.3 implement API signature for KrakenClientObj.GetDepositMethods as described here :
https://docs.kraken.com/rest/#section/Authentication/API-Sign

**Comment by JKorf** [comment]
Passing in EUR gives me an invalid asset error, which makes sense. Passing in XBT for bitcoin gives me the expected response. What version are you using?

**Comment by JRB202** [comment]
I am using V1.4.3 of KrakenExchange.Net
and V3.9.0 of CryptoExchange.Net

Passing EUR should return the information needed for EUR deposit on Kraken account (IBAN, BIC, ...)
This was working a few months ago
Can you reproduce the problem with this EUR code ?

**Comment by JKorf** [comment]
I don't see how this would have worked in a previous version, as it only supports crypto assets. Either way this library hasn't changed anything in this, so if something has changed its on Kraken' side. Closing this as I can't do anything about this.

**Comment by JRB202** [comment]
Which function is then supposed to be used for EUR deposits in order to
get IBAN to be used for Kraken ?
