### ISSUE TITLE
Unsubscribing Trade and Order updates doesn't work

### ISSUE THREAD

**Issue by rakewell** [JKorf/Kraken.Net#34]
SubscribeToOwnTradeUpdates
SubscribeToOrderUpdates

The close method on the subscription object returned from the above methods results in a channel not found error. The channel always seems to be 0 as well. Calling close on the price updates subscription works fine (the channel is not 0 on those subscriptions)

**Comment by JKorf** [comment]
Hi, thanks for the report. This will be fixed in next release.

**Comment by JKorf** [comment]
Fixed in latest version
