### ISSUE TITLE
Futures API support

### ISSUE THREAD

**Issue by plucked** [JKorf/Kraken.Net#35]
Hi there, 

I want to ask if you planning to add support for the futures API? 

If not, I would do it then and propose a PR. My Idea would be to make this in a separate client class to have a clear separation.

**Comment by danielhw2** [comment]
That would be great, I'm waiting for it... =)

**Comment by R00iBaard** [comment]
Did anything come of this?

**Comment by Digitalmatiq** [comment]
+1 I'm also interested in this

**Comment by danielhw2** [comment]
Thanks... Will implement in this weekend!
