### ISSUE TITLE
GetTradeVolume throws a JsonSerialization exception

### ISSUE THREAD

**Issue by evolinux** [JKorf/Kraken.Net#37]
**Bug description** 

**_GetTradeVolume_** fails to execute, on the Kraken REST client, throwing a JsonSerialization exception :
_Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Kraken.Net.Objects.KrakenFeeStruct]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object._

**To Reproduce**
```
KrakenClient KrakenRestClient = new KrakenClient(clientOptions);
var tradeVolumeResult = KrakenRestClient.GetTradeVolume(null, default, "XXBTZEUR");
if (!tradeVolumeResult.Success)
{
  Console.Write(tradeVolumeResult.Error);
}
```

**Expected behavior**

The **Fees** and **MakerFees** properties of class **KrakenTradeVolume** should be serialized in a Dictionary instead of a IEnumerable. That's because a **KrakenTradeVolume** is returned for each provided pair (string).

```
public class KrakenTradeVolume
{
    public Dictionary<string, KrakenFeeStruct> Fees { get; set; } = new Dictionary<string, KrakenFeeStruct>();
    [JsonProperty("fees_maker")]
    public Dictionary<string, KrakenFeeStruct> MakerFees { get; set; } = new Dictionary<string, KrakenFeeStruct>();
}
```

I can contribute and fix the issue. Just let me know if you want my help :)

**Comment by JKorf** [comment]
Fixed in latest version
