### ISSUE TITLE
Wrong order of currency pair names ([QuoteCurrency]/[BaseCurrency]) in KrakenHelpers.cs exception message

### ISSUE THREAD

**Issue by EpsilonD3lta** [JKorf/Kraken.Net#39]
**Describe the bug**
[QuoteCurrency]/[BaseCurrency] are in wrong order

**Expected behavior**
Order should be [BaseCurrency][QuoteCurrency] according to various sources, including:
https://support.kraken.com/hc/en-us/articles/115000364388-Trading-glossary

**Comment by JKorf** [comment]
Has been fixed in the latest version, thanks
