### ISSUE TITLE
Receiving messages in wrong handler

### ISSUE THREAD

**Issue by behappyall** [JKorf/Kraken.Net#4]
When subscribed to a marketdepth update for "_ETH/USD_", "_BTC/USD_", "_ETC/ETH_"). 
You can receive an update for some market in the wrong handler. (BTC/USD in ETC/ETH handler). 
I created a small demo project to reproduce this behavior: 
[Demo-project](https://github.com/behappyall/Kraken-Demo)

My Thought: Value ChanelId for updating BTC/USD depth [is 0] that is equal to a default of int value.

**Comment by behappyall** [comment]
Thanks a lot!

**Comment by JKorf** [comment]
Just an update, I've pushed version 0.0.4, should be available in a few minutes!
