### ISSUE TITLE
Can't subscribe to OrderBook (socket client)

### ISSUE THREAD

**Issue by PsykotropyK** [JKorf/Kraken.Net#45]
**Describe the bug**
Hello, following the [issue I have with Bitfinex](https://github.com/JKorf/Bitfinex.Net/issues/134), I tried to perform the same kind of logic with the Kraken implementation.
Unfortunately I can't subscribe to any order book, and two exceptions are thrown `Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll` (same exception for both).

**To Reproduce**
Reuse the same code logic as what I did in my Bitfinex issue, i.e. create a `KrakenClient` (tested with or without api keys/secret), a `KrakenSocketClient` and a `KrakenOrderBookOptions`. 
Create a `KrakenSymbolOrderBook` and subscribe to a Symbol (i.e. for instance `BTCEUR`).
The code is exactly the same as what I provided in the Bitfinex issue, just replacing all the Bitfinex classes by their Kraken equivalent

**Expected behavior**
The order book should be subscribed

**Debug logging**
Setting the Verbosity to Trace or Debug provides the same results:

2021/08/20 11:08:49:275 | Information | Kraken     | Kraken order book BTCEUR status changed: Disconnected => Connecting
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll

**Comment by JKorf** [comment]
The issue is probably that the symbol isn't correct for Kraken. Kraken uses XBT/EUR where Bitfinex uses tBTCEUR for the same symbol

**Comment by PsykotropyK** [comment]
Sorry for the annoyance. I actually made a complete symbol transliteration class in between the different exchanges but did not used it in my testing project...
