### ISSUE TITLE
Add support for snapshot parameter to SubscribeToOwnTradeUpdatesAsync

### ISSUE THREAD

**Issue by Raist007** [JKorf/Kraken.Net#50]
**Describe the bug**
ownTrades socket subscription support a "snapshot" parameter to decide whether a snapshot should be sent on subscription.
Today this parameter is not supported by SubscribeToOwnTradeUpdatesAsync

**To Reproduce**
Code review

**Expected behavior**
Ability to decide to receive or not a snapshot on ownTrades subscription

**Comment by JKorf** [comment]
Added in latest version
