### ISSUE TITLE
KrakenSocketClient, SubscribeToTickerUpdatesAsync doesn't work expected.

### ISSUE THREAD

**Issue by khaNuri** [JKorf/Kraken.Net#54]
**SubscribeToTickerUpdatesAsync take only one message.**
SubscribeToTickerUpdatesAsync send only one data at all and stoped without any exception.

            KrakenSocketClient.SetDefaultOptions(new KrakenSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials("KEY", "SECRET"),
                LogLevel = LogLevel.Debug,
                LogWriters = new List<ILogger> { new ConsoleLogger() }
            });

            var socketClient = new KrakenSocketClient();

            decimal lastBid = 0m;
            decimal lastAsk = 0m;

            socketClient.SubscribeToTickerUpdatesAsync("XRP/USDT", data =>
            {
                bool print = false;
                if (lastBid != data.Data.BestBids.Price)
                {

                    lastBid = data.Data.BestBids.Price;
                    print = true;
                }
                if (lastAsk != data.Data.BestAsks.Price)
                {
                    lastAsk = data.Data.BestAsks.Price;
                    print = true;
                }
                if (print)
                    Console.WriteLine($"Ask {lastAsk:N4} - Bid {lastBid:N4}");
            });

            Console.ReadLine();
            socketClient.UnsubscribeAllAsync();

![image](https://user-images.githubusercontent.com/3854564/137588880-604148f3-902e-42fe-b1d8-0708d80aa7d6.png)

**Comment by JKorf** [comment]
This works fine for me in the latest version. You'll probably want to `await`  the sub/unsub calls. If you put LogLevel to Trace you'll have more info on what the socket is receiving

**Comment by khaNuri** [comment]
Yes, You are right! The very slow data flow misled me.  I tought it must be same as Binance... I closed issue. Thanks.
