### ISSUE TITLE
Implement websocket ping/pong and heartbeat

### ISSUE THREAD

**Issue by EpsilonD3lta** [JKorf/Kraken.Net#55]
**Feature request**
Implement websocket ping/pong and heartbeat
https://docs.kraken.com/websockets/#message-ping

**Comment by kristophernguyen** [comment]
Why can't you use the available ping/pingAsync?

**Comment by JKorf** [comment]
I don't really see the need for a custom ping. Any particular use case?

**Comment by EpsilonD3lta** [comment]
Is there any other way to ping a server/check if the socket connection is alive? I could not find it.
And what about the heartbeat?

**Comment by EpsilonD3lta** [comment]
@kristophernguyen 
> Why can't you use the available ping/pingAsync?
Where are they available, I cannot find such methods anywhere
