### ISSUE TITLE
Multithreading Support

### ISSUE THREAD

**Issue by jaylagorio** [JKorf/Kraken.Net#56]
**Describe the bug**
When using Kraken.Net with multiple threads the `System.AggregateException: One or more errors occurred. (Unknown error (0xc1000008))` error is generated during hashing.

**To Reproduce**
This can be reproduced by making REST calls to file orders or get order status using the same instance from multiple threads.

**Expected behavior**
I would have expected these calls to work on independent threads because each thread isn't making calls about the same order.

**Debug logging**
Narrowed the code to reproduce down to here and found the same use in Kraken.Net: https://github.com/dotnet/runtime/issues/61417#issuecomment-980456899

**Comment by jaylagorio** [comment]
@JKorf It looks like there's a PR that fixes this, any thoughts on when you'll have a chance to do a new release so I can multithread my app? Thanks so much to you and @vcsjones!

**Comment by JKorf** [comment]
I've pushed a new version for this

**Comment by jaylagorio** [comment]
@JKorf Just wanted to let you know I've had this running multithreaded for the last few days and had no crashes. Thanks again!
