### ISSUE TITLE
OHLC

### ISSUE THREAD

**Issue by dharmatech** [JKorf/Kraken.Net#58]
Hello!

It looks like Kraken offers a way to get price history data via the following OHLC endpoint:

https://docs.kraken.com/rest/#operation/getOHLCData

Just wondering, is this data also available via this package?

I setup a simple test program with a client. Looking at the available methods on the client object, it wasn't clear to me which of these may be for the OHLC data:

![image](https://user-images.githubusercontent.com/20816/144148361-ffe305f3-0a0b-4fe1-a546-646dd7d0f27a.png)

Thanks!

**Comment by JKorf** [comment]
Hi, yes it is. Most exchanges call that data `Kline` or `Candlestick` data, so for uniformity it's available with the `GetKlinesAsync` method.

**Comment by dharmatech** [comment]
@JKorf 

Jan,

Thank you for taking the time to answer my question.

Sent you a little nano to help with lunch. 😊

https://nanocrawler.cc/explorer/block/D5297413BFA3698443148624A3BC59A7751019E5C920454B88D1E6EDD08E770F

**Comment by dharmatech** [comment]
Just in case others are curious about how to do get price history data, here's an example of asking for the BTCUSD data, with no specified start date and an interval of 15 days:

![image](https://user-images.githubusercontent.com/20816/144291886-07c8ddb2-e582-4da0-b0bc-299fb7f219f0.png)

Here's a similar example, but with an interval of 1 day. Note that the data starts at 2019.

![image](https://user-images.githubusercontent.com/20816/144292118-9fb2a17b-c2e3-4eb7-8eec-4829b5f63da4.png)

Note that if you ask for 1 day interval data going back to 2013, it only gives you the data starting at 2019:

![image](https://user-images.githubusercontent.com/20816/144292256-bbc59e5c-e02a-4f58-89dc-664d37b0c3c9.png)

1 hour data goes back about a month:

![image](https://user-images.githubusercontent.com/20816/144292477-b89719dc-77a7-4b62-819d-07b18055fb75.png)

1 minute data goes back less around 12 hours:

![image](https://user-images.githubusercontent.com/20816/144292665-56213bc4-795b-447c-8638-8400bd37d4a7.png)

**Comment by dharmatech** [comment]
Note that via Coinbase Pro API, it's possible to get 1 day data going back to 2014.

I have a video about this here:

https://youtu.be/Xl5vx9XFKyo

If anyone knows if it's possible to get the 1 day data going back to 2014 on Kraken, feel free to post below. :-)

**Comment by dharmatech** [comment]
OK, it looks like the historical data can be retrieved via the `Trades` endpoint:

https://support.kraken.com/hc/en-us/articles/218198197-How-to-retrieve-historical-time-and-sales-trading-history-using-the-REST-API-Trades-endpoint-

**Comment by dharmatech** [comment]
@JKorf 

Just FYI, I'm using your library as part of this project:

https://github.com/dharmatech/kraken-trades-database

The aim there is to retrieve the entire trading history for Kraken. I do so in two parts. First I ingest their downloadable historical CSV data. I then use your package to get the more recent trades data via API.

Thank you again for this library! Works very well.
