### ISSUE TITLE
WebSocket API will implement real time notification of deposits to Kraken account

### ISSUE THREAD

**Issue by JRB202** [JKorf/Kraken.Net#59]
Hi,

Chad from Kraken support wrote me this :

In addition, our **WebSocket API will shortly be upgraded to include an account balance feed, which could be used to receive a real time notification of deposits to your Kraken account**, so perhaps this would be a suitable alternative to a web hook or call back. We expect the account balance feed to be released within the next few weeks.

Do you intend to implement this new feature ?

Thanks

**Comment by JKorf** [comment]
Yes this will be implemented when it's available
