### ISSUE TITLE
missing enum/Ledger type

### ISSUE THREAD

**Issue by ludovicjul** [JKorf/Kraken.Net#60]
**Describe the bug**
Some ledger type are missing in the converter and ledgerentrytype enum, creating the code to crash  : 
"spend" "receive" "settled" 

**To Reproduce**
Retrieve ledger of any type below. with method : GetLedgerInfoAsync

**Expected behavior**
handle those new/changed ledger type

**Debug logging**
GetLedgerInfoAsync

=>update following enum with new Ledger Type and the converter as well. 
namespace Kraken.Net.Objects
    public enum LedgerEntryType

**Comment by JKorf** [comment]
Should be fixed in the latest version
