### ISSUE TITLE
Get OHLC Data End Time

### ISSUE THREAD

**Issue by Admiraliss** [JKorf/Kraken.Net#63]
MyKrakenClient.SpotApi.CommonSpotClient.GetKlinesAsync() End Date is not accepted
but working, like api documentation

https://api.kraken.com/0/public/OHLC?interval=60&pair=XXBTZEUR&since=1644704339&to=1644704409

https://support.kraken.com/hc/en-us/articles/4403284627220-OHLC

**Comment by JKorf** [comment]
The link you posted is for the Futures API , spot doesn't support an end parameter
