### ISSUE TITLE
Error :  WaitingForActivation

### ISSUE THREAD

**Issue by JRB202** [JKorf/Kraken.Net#64]
Since KrakenExchange.Net upgrade to V3.05

when using this Dot.Net VB syntax :

        Dim KrakenClientObj = New KrakenClient(New Objects.KrakenClientOptions)
        KrakenClientObj.ClientOptions.ApiCredentials = ReadKrakenAPIcredentials()

        Dim AssetSymbolList As List(Of String) = New List(Of String)
        AssetSymbolList.Add("EUR")

        Dim AssetsInfo = KrakenClientObj.SpotApi.ExchangeData.GetAssetsAsync(AssetSymbolList)

I get Status = WaitingForActivation and nothing in AssetsInfo.Result.data
instead of expected result

This syntax was working with previous V3 version
Obviously ReadKrakenAPIcredentials function is returning valid Kraken API Credentials in ApiCredentials

**Comment by JRB202** [comment]
I discovered that adding this line after GetAssetsAsync call solves the problem :
AssetsInfo .Wait()

It was not necessary in previous versions of KrakenExchange.Net

So, or this line is missing in your GetAssetsAsync code
or
Documentation is not accurate

What do you think ?

**Comment by JKorf** [comment]
This is not an issue with the library. The library is fully async, and you're trying to use it synchronically
