### ISSUE TITLE
PlaceOrder Websocket method does not have the orderFlags parameter

### ISSUE THREAD

**Issue by DocteurRe** [JKorf/Kraken.Net#65]
The PlaceOrderAsync method in websocket does not have the orderFlags parameter, even though it is available in the Kraken websocket API.

The PlaceOrderAsync method in REST have the orderFlags parameter correctly implemented though. I use it as a workaround now, but using websocket would be faster.

**Comment by JKorf** [comment]
Hi, I've added the flags parameter in the socket PlaceOrderAsync method in the latest version
