### ISSUE TITLE
SubscribeToTickerUpdatesAsync doesn't get new data on best bid / best ask changes

### ISSUE THREAD

**Issue by yanivshaked** [JKorf/Kraken.Net#66]
**Describe the bug**
Using SubscribeToTickerUpdatesAsync, I'm subscribing to "BTC/USD" ticker updates while following the best bid / best ask updates for the same symbol on https://trade.kraken.com/charts/KRAKEN:BTC-USD.
It seems that the action provided on SubscribeToTickerUpdatesAsync doesn't get called when best bid / best ask are updates, only when last trade is updated.

**To Reproduce**
```
	var cr = await client.SpotStreams.SubscribeToTickerUpdatesAsync("BTC/USD", d =>
	{
		d.Timestamp.Dump($"BestAsk:{d.Data.BestAsks.Price} BestBid:{d.Data.BestBids.Price}");
	});

	cr.Success.Dump();
	Console.ReadLine();
	client.Dispose();
```

![image](https://user-images.githubusercontent.com/13107481/164419479-b7aa25e3-dc4f-4c9a-b92a-81623a8818d6.png)

**Expected behavior**
Expecting updates also on BestAsk/BestBid changes.

**Comment by yanivshaked** [comment]
@JKorf Can you please shed some light on this issue?

**Comment by JKorf** [comment]
Hi, I think the ticker updates might be throttled and it might not update real time. If you're looking for real time best bid/ask info you could subscribe using the `SubscribeToSpreadUpdatesAsync` method.
Hope that helps

**Comment by yanivshaked** [comment]
Thanks @JKorf , it works as expected!
