### ISSUE TITLE
AggregateException for valid T/EUR symbol

### ISSUE THREAD

**Issue by Bunnywood** [JKorf/Kraken.Net#67]
Hi,

I'm getting this exception:

`System.AggregateException: 'One or more errors occurred. (T/EUR is not a valid Kraken websocket symbol. Should be [BaseAsset]/[QuoteAsset] in ISO 4217-A3 standardized names, e.g. ETH/XBTWebsocket names for pairs are returned in the GetSymbols method in the WebsocketName property.)'
`

when calling 
`KrakenClient.SpotStreams.SubscribeToTickerUpdatesAsync`

and using the list of symbols retrieved using
`KrakenRestClient.SpotApi.ExchangeData.GetSymbolsAsync`

T/EUR is the record returned, a BaseAsset of T and a QuoteAsset of ZEUR. I'm guessing that this is a new pair recently added to the Kraken service, so maybe some work is required in the validator?

Many Thanks.

**Comment by JKorf** [comment]
Hi, thanks for the report, I've fixed this in the latest version
