### ISSUE TITLE
WebKrakenClient.SpotApi.Trading.PlaceOrderAsync fails if validatingOnly = true

### ISSUE THREAD

**Issue by evolinux** [JKorf/Kraken.Net#70]
**Describe the bug**
_API WebKrakenClient.SpotApi.Trading.PlaceOrderAsync_ throws a "Sequence contains no elements" exception when argument `validatingOnly=true`

**To Reproduce**
Execute _API WebKrakenClient.SpotApi.Trading.PlaceOrderAsync_  with `validatingOnly=true`.

**Expected behavior**
OrderId not returned by the call because no order is actually placed but just send for validation.

**Solution**
Use `result.Data.OrderIds.FirstOrDefault()` to catch a null OrderId in case `validatingOnly=true`.

**Comment by JKorf** [comment]
Has been fixed
