### ISSUE TITLE
KrakenSocketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync not accepting array of symbol strings

### ISSUE THREAD

**Issue by BscuserXYZ** [JKorf/Kraken.Net#72]
**Describe the bug**
The method KrakenSocketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync is not accepting an array of symbol strings. It is only accepting one symbol string. It is not possible to subscribe to multiple symbol orderbooks at once.

https://docs.kraken.com/websockets/#message-subscribe says that an array is supported. 

pair | array | Optional - Array of currency pairs. Format of each pair is "A/B", where A and B are ISO 4217-A3 for standardized assets and popular unique symbol if not standardized.

**To Reproduce**
Connect with Kraken Websocketclient and subscribe to the orderbook

**Expected behavior**
I would expect that an array of strings would be accepted so i can subscribe to multiple orderbook symbols at once on Kraken.

**Comment by JKorf** [comment]
Has been fixed in V3.1.4
