### ISSUE TITLE
Same Rate limiter shared across multiple kraken clients

### ISSUE THREAD

**Issue by trekco** [JKorf/Kraken.Net#76]
**Describe the bug**
I have multiple kraken API keys; I instantiate a client for each key. All the clients share the same rate limiter.

After 15 requests all the clients are rate limited where it should rate limited be by key.

**To Reproduce**
1. Create 2 kraken clients with different api keys. 
2. Make multiple requests with one client in a short time until you are rate limited. 
3. Make a request with another client, you will see that that client is now also rate limited

**Expected behavior**
Client 1 should not affect client 2's rate limiter

**Comment by trekco** [comment]
Below is my workaround for the problem. I Instantiate a new `RateLimeter` for each client. This solution works but it is not nice having to do this.


```
private KrakenClient CreateClient(string key, string secret)
{
	var restOpt = new RestApiClientOptions(KrakenApiAddresses.Default.RestClientAddress)
	{
		RateLimiters = new List<IRateLimiter>
		{
			new RateLimiter()
				.AddApiKeyLimit(15, TimeSpan.FromSeconds(45), false, false)
				.AddEndpointLimit(new[] { "/private/AddOrder", "/private/CancelOrder", "/private/CancelAll", "/private/CancelAllOrdersAfter" }, 60, TimeSpan.FromSeconds(60), null, true)
		}
	};

	var opt = new KrakenClientOptions
	{
		ApiCredentials = new ApiCredentials(key, secret),
		SpotApiOptions = restOpt
	};

	return new KrakenClient(opt);
}
```

**Comment by JKorf** [comment]
Should be fixed in the latest version, let me know if you have any issues

**Comment by trekco** [comment]
@JKorf It is working now as expected, thank you very much
