### ISSUE TITLE
Missing endpoint method GetWithdrawStatusAsync

### ISSUE THREAD

**Issue by masherak** [JKorf/Kraken.Net#78]
Hello, in the interface "IKrakenClient" I can see method "GetDepositStatusAsync" but there is no "GetWithdrawStatusAsync".

There is endpoint:
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/15813908/231264389-fcc01605-ef03-4775-b6d6-55dc519bf208.png">

**Comment by masherak** [comment]
@JKorf Can you help me? Or I should try to do it and send PR ?

**Comment by JKorf** [comment]
I'm currently in the process of updating the libraries, should be a small effort to add this in in the coming days

**Comment by JKorf** [comment]
I've added it in the latest version!
