### ISSUE TITLE
Trading agreement required on german accounts

### ISSUE THREAD

**Issue by imdbere** [JKorf/Kraken.Net#8]
Hello,
There seems to be a strange policy on Kraken where on accounts in Germany, 
an additional parameter is needed when calling the AddOrder endpoint.
See: [https://support.kraken.com/hc/en-us/articles/360000920026-Trading-agreement-required-error](https://support.kraken.com/hc/en-us/articles/360000920026-Trading-agreement-required-error)

I think the only thing necessary to fix this would be to add a static trading_agreement = 'agree'
parameter to the PlaceOrderAsync method since i don't think that this would interfere with non-german accounts.
Thanks

**Comment by JKorf** [comment]
Thanks for the report, I've added the parameter and pushed a new version, should be available in a few minutes

**Comment by imdbere** [comment]
Wow, that was fast, thank you very much :)
