### ISSUE TITLE
GetOpenOrdersAsync() not returning the StopPrice

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Kraken.Net#81]
When I call `ClienteRest.FuturesApi.Trading.GetOpenOrdersAsync()` and the result is a `"orderType": "Stop"` the `StopPrice` does not show up, but in the `OriginalData` it does:

"Data": [
    {
      "cliOrdId": "xxx...",
      "filledSize": 0.0,
      "lastUpdateTime": 1688924551153,
      "limitPrice": null,
      "order_id": "xxx...",
      "Quantity": 1.0,
      "unfilledSize": 1.0,
      "ReduceOnly": true,
      "Side": "Sell",
      "Symbol": "fi_xbtusd_230728",
      "receivedTime": 1688924551153,
      "orderType": "Stop",
      "Status": "Untouched"
    }
  ],
  "OriginalData": 
  "{\"result\":\"success\",\"openOrders\":[{\"order_id\":\"xxx...\",\"cliOrdId\":\"xxx...\",\"symbol\":\"fi_xbtusd_230728\",\"side\":\"sell\",\"orderType\":\"stop\",\"stopPrice\":29259,\"unfilledSize\":1,\"receivedTime\":\"2023-07-09T17:42:31.153Z\",\"status\":\"untouched\",\"filledSize\":0,\"reduceOnly\":true,\"triggerSignal\":\"mark\",\"lastUpdateTime\":\"2023-07-09T17:42:31.153Z\"}],\"serverTime\":\"2023-07-09T17:55:26.179Z\"}",

**Comment by JKorf** [comment]
Thanks for the data, I've added it in the latest version. Let me know if you find other issues
