### ISSUE TITLE
TickSize is always null

### ISSUE THREAD

**Issue by NuclearRazor** [JKorf/Kraken.Net#82]
Hi, I have working with Kraken.NET library, and it's very nice to use.
I need a symbol info for my special storage. I use a KrakenSymbol (Kraken.Net.Objects.Models).

For some of the calculations, I need to use a symbol **TickSize** field. I understand that it could be a null, by default, because it is declared in the next way:
`public decimal? TickSize { get; set; }`

But during debugging I saw that all symbols, that I checked, have a null value for TickSize. 

I am using this call to receive symbols info:

```
_client = new KrakenRestClient(options =>
{
    options.ApiCredentials = new ApiCredentials(_configurationService.Key, _configurationService.Secret);
});
var result = await _client.SpotApi.ExchangeData.GetSymbolsAsync();
```

For example, for XBTUSD asset pair it returns:
```
AlternateName	"XBTUSD"	string
BaseAsset	"XXBT"	string
BaseAssetClass	"currency"	string
Decimals	1	int
FeeAsset	"ZUSD"	string
...
QuoteAsset	"ZUSD"	string
QuoteAssetClass	"currency"	string
ShortPositionLimit	200	int
Status	"online"	string
TickSize	null	decimal?
VolumeLotSize	"unit"	string
WebsocketName	"XBT/USD"	string
```

By direct API call:
https://api.kraken.com/0/public/AssetPairs?pair=XBTUSD

`{"error":[],"result":{"XXBTZUSD":{"altname":"XBTUSD","wsname":"XBT/USD","aclass_base":"currency","base":"XXBT","aclass_quote":"currency","quote":"ZUSD","lot":"unit","cost_decimals":5,"pair_decimals":1,"lot_decimals":8,"lot_multiplier":1,"leverage_buy":[2,3,4,5],"leverage_sell":[2,3,4,5],"fees":[[0,0.26],[50000,0.24],[100000,0.22],[250000,0.2],[500000,0.18],[1000000,0.16],[2500000,0.14],[5000000,0.12],[10000000,0.1]],"fees_maker":[[0,0.16],[50000,0.14],[100000,0.12],[250000,0.1],[500000,0.08],[1000000,0.06],[2500000,0.04],[5000000,0.02],[10000000,0.0]],"fee_volume_currency":"ZUSD","margin_call":80,"margin_stop":40,"ordermin":"0.0001","costmin":"0.5","tick_size":"0.1","status":"online","long_position_limit":250,"short_position_limit":200}}}`

Does this library support TickSize or it's really a bug?

Kraken.Net runtime library version:
v4.0.30319

Version:
v4.0.0.0

**Comment by JKorf** [comment]
Hi, this was a bug yes. Fixed in the latest version

**Comment by NuclearRazor** [comment]
Thanks! Going to check very soon.
