### ISSUE TITLE
Possible type bug for Quantity parameter in PlaceOrderAsync method on KrakenRestClientFuturesApiTrading

### ISSUE THREAD

**Issue by chdierckx** [JKorf/Kraken.Net#87]
**Describe the bug**
The quantity parameter in PlaceOrderAsync method on KrakenRestClientFuturesApiTrading is of integer type. I've tested the Kraken API call manually with decimal value and the order with correct decimal size was accepted succesfully.

**To Reproduce**
Use a decimal value for quantity parameter in PlaceOrderAsync method on KrakenRestClientFuturesApiTrading.

**Expected behavior**
To be able to use a decimal value for quantity parameter. For instance I want to be able to buy 9.56 SOL on PF_SOLUSD market.

**Debug logging**
No debug logging available.

Thanks in advance. I like the new Kraken Futures implementation!

**Comment by JKorf** [comment]
Hm thats weird. On futures you're trading contracts, where 1 contract is x amount of asset. How would you buy .56 contract? Not sure how that is handled by Kraken though, I'll try it when I have some time

**Comment by chdierckx** [comment]
Thanks! This post to give you some more context.

Screenshot from Kraken Pro UI of a fractional buy of a Perpetual Futures contract (PF_SOLUSD): [Kraken Pro UI](https://ibb.co/cg3Zx1n)

(Confusing) Screenshots from Kraken Futures API docs where SendOrder responses show both int and decimal value examples: [Kraken Futures SendOrder Api docs](https://ibb.co/1bJt6C4)

Usage of decimal quantity in other Futures Exchange clients. For instance [Binance USD Futures Trading API](https://github.com/JKorf/Binance.Net/blob/master/Binance.Net/Clients/UsdFuturesApi/BinanceRestClientUsdFuturesApiTrading.cs) line 68

**Comment by Temppus** [comment]
Found same bug when toying around some order placement yesterday. I have created order manually and was trying to close it via API call but position was very small < 1, but due to quantity in PlaceOrderAsync was integer it was rounded to 0 and API request failed. I did my extension implementation of this method and it works with decimal totally fine and I was able to close it.

**Comment by JKorf** [comment]
Has been changed to decimal some time ago
