### ISSUE TITLE
Add support for Spot FIX API

### ISSUE THREAD

**Issue by R00iBaard** [JKorf/Kraken.Net#93]
Hey,

Many thanks for such a wonderful library. Do you have any intentions in adding support for the FIX (financial information exchange) API Protocol offered by kraken exchange?

https://docs.kraken.com/fix/docs/general/fix-intro

**Comment by JKorf** [comment]
Hi,

Not currently no. As I'm quite limited in time I have to choose what to work on. And as I'm sure you understand adding another protocol which allows for pretty much the same functionality isn't at the top of the list ;)

**Comment by R00iBaard** [comment]
> Hi,
> 
> Not currently no. As I'm quite limited in time I have to choose what to work on. And as I'm sure you understand adding another protocol which allows for pretty much the same functionality isn't at the top of the list ;)

100% Agree.
Many thanks
