### ISSUE TITLE
SubscribeToKlineUpdatesAsync updates are sent randomly 

### ISSUE THREAD

**Issue by rrkpt** [JKorf/Kraken.Net#96]
SubscribeToKlineUpdatesAsync for Spot market updates are sent randomly without the possibility of identifying end of the candle.

**To Reproduce**
Subscribe to KLine
await _socketClient.SpotApi.SubscribeToKlineUpdatesAsync(instrument, KlineInterval.OneMinute, t => OnKlineUpdates(t, instrument, action));

**Expected behavior**
 OnKlineUpdates are called once at the very beginning of the minute, or there is ability to identify that candle has build

**Comment by JKorf** [comment]
This is an 'issue' on the server side
