### ISSUE TITLE
SubscribeToUserTradeUpdatesAsync returning all past trades

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Kraken.Net#97]
**Describe the bug**
When I call `client.FuturesApi.SubscribeToUserTradeUpdatesAsync` it returns all past historic trades. In the response there is no information about if the trade is new or old, only the "time/TimeSpan". 

**To Reproduce**
Just call SubscribeToUserTradeUpdatesAsync() and handle the response event.

**Expected behavior**
It should only receive new trade events. As a workaround I filtering the trades older than a especific time.

**Debug logging**
The trade list array is in `data.Data.Trades`.

CryptoExchange.Net 7.0.0
KrakenExchange.Net 4.3.0
.Net 8

**Comment by rakewell** [comment]
This is also happening for `SpotApi.SubscribeToUserTradeUpdatesAsync(token, false`.. it does not seem to observe the snapshot parameter

**Comment by JKorf** [comment]
For both spot and futures you can look at the UpdateType property of the update
```csharp
await krakenSocketClient.FuturesApi.SubscribeToUserTradeUpdatesAsync(data =>
{
    if (data.UpdateType == SocketUpdateType.Snapshot)
    {
        // Handle snapshot
    }
    else
    {
        // Handle new trade
    }
});
```
