### ISSUE TITLE
Error with parameter secondaryPrice = null in KrakenSocketClient.SpotApi.PlaceOrderAsync

### ISSUE THREAD

**Issue by vincentbillardfr** [JKorf/Kraken.Net#99]
When calling KrakenSocketClient.SpotApi.PlaceOrderAsync with secondaryPrice = null, I get an error "Price2 field must be a string".
This problem appeared recently with last versions, it always worked well at least until version 4.3.0 of the library.
Maybe there will be the same problem with other parameters.

I'll try to investigate when I'll have free time, but maybe it will be easy for you to find the problem as you know well your source code

**Comment by JKorf** [comment]
Thanks for the report. This indeed broke during some of the refactoring; null value fields were no longer ignored while they were before. I've fixed it in the latest version
